// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/eve.ts";
import * as module_2 from "../../agent/tools/check_bike_stock.ts";
import * as module_3 from "../../agent/tools/get_catalog.ts";
import * as module_4 from "../../agent/tools/search_faq.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "tools/check_bike_stock.ts": module_2,
                  "tools/get_catalog.ts": module_3,
                  "tools/search_faq.ts": module_4
                })
            })
    })
});

export default moduleMap;
